### ISSUE TITLE
Omni-quotes doesn't work

### ISSUE THREAD

**Issue by VisionaryAppDev** [AdrieanKhisbe/omni-quotes.el#2]
Hi, 
I have tried this package recently and I am not sure if this package still work because I got some error when I tried to enable omni-quotes-mode or omni-quotes-display-random-quote. The error output is:

`Warning (emacs): There is no logger of name 6703.
` 

Not sure what is going on.

**Comment by AdrieanKhisbe** [comment]
@VisionaryAppDev 
_Sorry for the late answer_

This is Strange, Strange.
What version of emacs are you using?

**Comment by VisionaryAppDev** [comment]
I compile the latest version from Emacs Master branch in github so it should be 27.

**Comment by AdrieanKhisbe** [comment]
arf, There must be some breaking change.
so far the library is tested up to 25.1
I'm going to try to have a look into it in the days to come

**Comment by VisionaryAppDev** [comment]
I use this one to install the latest version. it may help you too ...
https://www.reddit.com/r/emacs/comments/7c0ry9/insall_emacs_27_from_source_ubuntu_1710_notes/

**Comment by mtekman** [comment]
Just chirping in to say that I am seeing this in `emacs 26.3` and `emacs 28.0.50` specifically with Swiper

**Comment by cjk** [comment]
It recently happened to me too - using Emacs 28.0.50
Swiper became unusable.

**Comment by aladine** [comment]
It happened to my emacs version too - Version 27.0.50

**Comment by seblemaguer** [comment]
I have it too for version 26.3 as well but I see it with paradox, swiper. I manage to pinpoint this to the fact that swiper and paradox are both using the function `log` in a mathematical way! so the problem is actually coming from omni-log. I think the function `log` should be renamed to avoid conflict with the library `calc`

**Comment by AdrieanKhisbe** [comment]
📤  New version released (on melpa and melpa stable),

I invite you @VisionaryAppDev, @mtekman, @cjk, @aladine  and @seblemaguer to try it and tell me if it solves your respectives issues.

**Comment by seblemaguer** [comment]
Seems good on my side

**Comment by VisionaryAppDev** [comment]
There is an error on my side. Here is some output.
```
Filename does not exists ~/.my-quote
omni-quotes-display-random-quote
Omni-Quotes mode disabled
Omni-Quotes mode enabled
Error running timer ‘omni-quotes-idle-display-callback’: (error "Accessing an empty ring")
GNU Emacs 28.0.50 (build 7, x86_64-pc-linux-gnu, GTK+ Version 3.24.14, cairo version 1.17.3) of 2020-02-19
```

Note sure if i have to do something before enable Omni Quotes mode. Let me know if i forget something.

**Comment by AdrieanKhisbe** [comment]
@VisionaryAppDev it's about the quote file, 

I supposed you copy paste the suggested configuration without changing the quote file:

cf the `.my-quote` in

```lisp
(use-package omni-quotes
  :bind (("M-s q m" . omni-quotes-mode)
         ("M-s q p" . omni-quotes-prev-set)
         ("M-s q n" . omni-quotes-next-set)
         ("M-s q s" . omni-quotes-shuffle-current-set)
         ("M-s q q" . omni-quotes-display-random-quote))
  :config (omni-quotes-load-simple-quote-file "~/.my-quote" "personal")) ; <---- THERE
```

You either need to create a `.my-quote` file, either point to some other file of your,
or remove :config section.

**Comment by mtekman** [comment]
@AdrieanKhisbe Partial luck on my side (Emacs 26.3 build 1)

Here is my entire emacs config (after deleting everything in my elpa folder):

```elisp
(setenv "LANG" "en_GB.UTF8")
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "https://elpa.gnu.org/packages/")
        ("org" . "https://orgmode.org/elpa/")))

(package-initialize)
(require 'package)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package omni-quotes)
(use-package swiper
  :ensure t
  :config
  (setq ivy-ignore-buffers '("\\` " "\\`\\*" "magit*"))
  :bind (("C-S-s" . swiper)
         ("C-x C-b" . ivy-switch-buffer)))
```
The only message I get is `Error (use-package): Cannot load omni-quotes` in the `*Warnings*` buffer.


*****

Finding this odd, I then do `package-refresh-contents RET package-install RET omni-quotes` and both work fine.

I'm not sure why the `use-package` method wont work but the regular install does

**Comment by aladine** [comment]
For my Emacs, the new fix works perfectly now after update from Melpa.

**Comment by AdrieanKhisbe** [comment]
@mtekman Very strange indeed. might be related to some caching on your machine as I tried to reproduce using `evm` to get good emacs version, and failed to do so:

I got the config you provided stored in a file, and ran the following commands:
```bash
evm install emacs-26.3
emacs -Q -nw -l .tmp.el
```
It was working fine. 🤔

**Comment by AdrieanKhisbe** [comment]
According to your answers @VisionaryAppDev, @mtekman, @cjk, @aladine and @seblemaguer, 
I will consider this issue as resolved.

I'll answer to the potential pending glitch to @mtekman and @VisionaryAppDev, on this issue even if closed, but for any other matter that might raise, please open a new issue.

Thanks
